name: Unit Test nmma
on:
  push:
    branches: [main]
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'doc/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - name: Checkout branch being tested
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Restore SVD models from cache
      uses: actions/cache@v3
      with:
        path: svdmodels
        key: svdmodels-${{ runner.os }}-${{ hashFiles('**/LICENSE') }}
        restore-keys: svdmodels-${{ runner.os }}-
    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -m pip install --upgrade pip setuptools wheel
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: pip cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-2-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-2-
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y openmpi-bin libopenmpi-dev gfortran build-essential libblas3 libblas-dev liblapack3 liblapack-dev libatlas-base-dev texlive texlive-latex-extra texlive-fonts-recommended dvipng cm-super
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install openmpi gfortran
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade git+https://github.com/bitranox/wrapt_timeout_decorator.git
        python -m pip install pytest pytest-cov flake8 pytest-aiohttp sqlparse freezegun PyJWT joblib tensorflow afterglowpy coveralls
        python -m pip install .
    - name: Install MultiNest
      run: |
        git clone https://github.com/JohannesBuchner/MultiNest && cd MultiNest/build && cmake .. && make && cd ../..
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude docs
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude docs,versioneer.py,nmma/_version.py,nmma/tests,nmma/*/__init__.py
    - name: Set up PostgreSQL (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y postgresql
        sudo systemctl start postgresql.service
        sudo -u postgres createuser --superuser $USER
        createdb nmma
    - name: Set up PostgreSQL (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew services start postgresql
        createdb nmma
    - name: Initialize database
      run: |
        echo "localhost:5432:*:$USER:anything" > ~/.pgpass
        chmod 600 ~/.pgpass
        psql -d nmma -c "GRANT ALL PRIVILEGES ON DATABASE nmma TO $USER;"
    - name: Test with pytest
      run: |
        python -m coverage run --source nmma -m pytest nmma/tests/*.py
      env:
        LD_LIBRARY_PATH: .:/home/runner/work/nmma/nmma/MultiNest/lib
    - name: Run Coveralls
      if: ${{ success() }}
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
